---
language: ruby
bundler_args: --without development
before_install:
  - curl getpuppet.whilefork.com > install_puppet.sh
  - bash install_puppet.sh $PUPPET_VERSION
  - puppet module build
  - puppet module install pkg/Ziaunys-tessera-*.tar.gz
rvm:
  - 1.9.3
env:
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
script:
  puppet apply --verbose tests/init.pp
